//States pins for stepper controls

#ifndef ROTOR_DEFINITIONS_H
#define ROTOR_DEFINITIONS_H

#define STEPPERV_DIR_PIN 8
#define STEPPERV_STEP_PIN 6
#define STEPPERV_ENABLE_PIN 4

#define STEPPERV_MAX_SPEED 4800.0
#define STEPPERV_MAX_ACCELERATION 1000.0

#define STEPPERH_DIR_PIN 2
#define STEPPERH_STEP_PIN 0
#define STEPPERH_ENABLE_PIN 1

#define STEPPERH_MAX_SPEED 4800.0
#define STEPPERH_MAX_ACCELERATION 1200.0

#define microStepRate 8

#define LIMIT_UP 90
#define LIMIT_DOWN -30

#define HORIZONTA_CALIBRATION_OFFSET 180

#endif
